# Recomanació basada en PageRank

L'algorisme PageRank, famós per l'ús en el cercador de Google, te moltes altres aplicacions. Un exemple d'ells és la recomanació d'items a usuaris basat en les similituds entre usuaris.

Recordeu el principi de funcionament bàsic de les recomanacions colaboratives basades en l'usuari, obtenim una puntuació per a un item i usuari, basat en les similituds d'aquest usuari amb la resta, i respectives puntuacions. Si ho formulem, podríem dir que tot es basa en:

$$\hat{r}_{u,i} = \frac{\sum_{v,v\neq u} sim(u,v) \cdot r_{v,i}}{\sum_{v,v\neq u} sim(u,v)}$$

Amb notació 

* $r_{u,i}$ ens indica la puntuació ($r$ating) de l'usuari $u$ a l'item $i$. 
* El sumatori $\sum_{v,v\neq u}$ indica la suma per cada usuari $v$ que no sigui el propi $u$ del que estem intentant predir una puntuació
* El barret a $\hat{r}$ denota que es tracta d'una predicció, el valor que estem intentant inferir a partir de les dades.

La funció $sim$ és la que ens indica quan semblants són dos usuaris entre sí. Tal i com heu vist a teoria, això es pot fer amb mètriques com la distància euclidea o la similitud de Pearson, d'entre moltes altres. En aquesta pràctica, però, veure'm com el vector obtingut a partir de calcular PageRank sobre una matriu concreta d'usuaris i items, també ens proporciona una mesura de similitud significativa.

## Bibliografia

Per aquells interesats, tota la informació relativa a PageRank està basada en la publicació

`Bryan, K., & Leise, T. (2006). The $25,000,000,000 eigenvector: The linear algebra behind Google. Siam Review, 48(3), 569-581.`

I els algorismes matemàtiques en el llibre:

`Applied numerical linear algebra, James W. Demmel`, capítol 4.4 

# PageRank

Aquesta cel·la serveix com a una breu recapitulació de l'algorisme PageRank vist a teoria. Recordem que PageRank es basa en trobar l'importància de les pàgines en base a la reputació d'aquestes i del número de links entrants i sortints.

Supossa que tenim la següent estructura de pàgines:

<img src="img/page1.png" />

És a dir, si comptem el número de `in-link` (enllaços d'entrada) de cada pàgina $x$, obtindríem:
$$x_1=3,x_2=2,x_3=1,x_4=3$$

Però també podem expressar-ho en funció de la pàgina de qui rebem el link, de forma que tinguem la importància en compte:

$$x_{entrada} = \dfrac{x_{sortida}}{|x_{sortida}|}$$

Per exemple, si ho apliquem a $x_1$, $x_1 = x_2 / 2 + x_3 / 2 + x_4 / 3$. De forma semblant, podem aplicar-ho a la resta:

$$x_1 = x_2 / 2 + x_3 / 2 + x_4 / 3$$
$$x_2 = x_1 / 2 + x_4 / 3$$
$$x_3 = x_4 / 3$$
$$x_4 = x_1 / 2 + x_2 / 2 + x_3 / 2$$

Ara podríem resoldre aquest sistema per trobar quina és la importància de cada web, un vector $(s_1,s_2,s_3,s_4)$. Però, resoldre-ho no és trivial (no en casos on tenim milions de webs, és clar!). Per tal de poder avançar, el que se sol fer és resoldre-ho en forma matricial:

$$
\begin{array}{ccc}
& \text{Out-links} &\\
G = &\begin{bmatrix}
    0 & 1/2 & 1/2 & 1/3 \\
    1/2 & 0 & 0 & 1/3 \\
    0 & 0 & 0 & 1/3 \\
    1/2 & 1/2 & 1/2 & 0
\end{bmatrix} & \text{In-links}
\end{array}
$$

El sistema ara es converteix en una equació, arquetip fàcilment reconegut pels matemàtics:

$$x = Gx$$

Trobareu els detalls a la publicació si esteu interesats, realment el que estem intentant és trobar el vector propi que té per valor propi 1. És a dir, resoldre $\lambda x = Gx$ tal que $\lambda = 1$

## Trobant el vector propi

Un dels mètodes més eficients, tot i que no el que més, és el mètode de la potència. Aquest, permet trobar el vector propi que té el valor propi més alt (coses de les matemàtiques, es pot demostrar que $\lambda=1$ serà el més alt). El mètode diu així:

$
i = 0\\
\text{do}\\
\hspace{2cm}y_{i+1} = Gx_i\\
\hspace{2cm}x_{i+1} = y_{i+1} / ||y_{i+1}||_2\\
\hspace{2cm}i = i + 1\\
\text{until }||x_{i+1} - x_{i}|| < 10^{-6}
$

On $x_0$ és un vector normalitzat amb suma 1, per exemple si tenim $n$ webs en total $x_0 = \textbf{1} / n$, on $\textbf{1}$ és un vector d'1s de tamany $n$.

**Programa l'algorisme del mètode de la potència amb numpy, seguint el pseudocodi de dalt**

In [1]:
import numpy as np


def power_method(G):
    """
    Donada una matriu d'adjecències, en calcula el PageRank.
    Mitjançant el mètode de la potència troba el vector propi
    de valor propi màxim (1)
    
    :param G: Matriu a calcular el PageRank
    :return: Vector d'importàncies del PageRank (vector
        propi amb valor propi més alt)
    """
    
    x_i = np.ones(G.shape[0])/G.shape[0] # we first create an array with the shape of G, filled with ones and then 
                                         # divided by the shape of G
    # we calculate the first iteration "manually"
    x = G.dot(x_i) # we multiply the matrices
    x = x/np.linalg.norm(x) # and we divide the matrice by its norm
    
    while(sum(np.absolute(x-x_i))>(10**(-6))): # while the sum of values isnt lesser than 10^-6 
        x_i = x  # we update our x matrice
        x = G.dot(x_i) # we multiply the matrices
        x = x/np.linalg.norm(x) # and we divide the matrice by its norm

    return (x) # we return the result
        
def solve_eig(G):
    """
    Calcula els vectors i valors propis de la matriu G
    mitjançant funcions de numpy. Funció de referència
    que us pot servir per comprovar que el vostre mètode
    power_method retorna el que toca.
    
    :param G: Matriu a calcular el PageRank
    :return: Vector d'importàncies del PageRank (vector
        propi amb valor propi més alt)
    """
    vals, vecs = np.linalg.eig(G)
    idxs = np.argsort(np.real(vals))
    return np.abs(vecs[:, idxs[-1]])

In [2]:
if __name__ == '__main__':
    G1 = np.asarray((
        (0,     1/2.0, 1/2.0, 1/3.0), 
        (1/2.0, 0,     0,     1/3.0), 
        (0,     0,     0,     1/3.0), 
        (1/2.0, 1/2.0, 1/2.0, 0)
    ))
    x = power_method(G1)
    y = solve_eig(G1)
    
    print(np.round(G1, 2))
    print('Eigenvector', np.round(x, 2))
    print('Eigenvector', np.round(y, 2))
    print('Eigenvalues', np.round(np.linalg.eigvals(G1), 2))

[[ 0.    0.5   0.5   0.33]
 [ 0.5   0.    0.    0.33]
 [ 0.    0.    0.    0.33]
 [ 0.5   0.5   0.5   0.  ]]
Eigenvector [ 0.56  0.49  0.21  0.63]
Eigenvector [ 0.56  0.49  0.21  0.63]
Eigenvalues [ 1.0+0.j -0.0+0.j -0.5+0.j -0.5-0.j]


## Casos extrems

Evidentment, no tot és tant bonic com sembla... Crea la matriu de la següent configuració i prova que passa quan n'executes el mètode de la potència:

<img src="img/page2.png" />

In [3]:
if __name__ == '__main__':
    G2 = np.asarray((
        (0,     1/2.0, 1/2.0, 0,   0), 
        (1/2.0, 0,     1/2.0, 0,   0), 
        (1/2.0, 1/2.0, 0,     0,   0), 
        (0,     0,     0,     0,   1.0),
        (0,     0,     0,     1.0, 0)
    ))
    x = power_method(G2)
    y = solve_eig(G2)
    
    print(np.round(G2, 2))
    print('Eigenvector', np.round(x, 2))
    print('Eigenvector', np.round(y, 2))
    print('Eigenvalues', np.round(np.linalg.eigvals(G2), 2))

[[ 0.   0.5  0.5  0.   0. ]
 [ 0.5  0.   0.5  0.   0. ]
 [ 0.5  0.5  0.   0.   0. ]
 [ 0.   0.   0.   0.   1. ]
 [ 0.   0.   0.   1.   0. ]]
Eigenvector [ 0.45  0.45  0.45  0.45  0.45]
Eigenvector [ 0.    0.    0.    0.71  0.71]
Eigenvalues [-0.5  1.  -0.5  1.  -1. ]


I encara en trobem un més de cas extrem:

<img src="img/page3.png" />

In [4]:
if __name__ == '__main__':
    G3 = np.asarray((
        (0,   0, 1/2.0, 0), 
        (0,   0, 1/2.0, 0), 
        (1.0, 0, 0,     0), 
        (0,   0, 0,     0)
    ))
    #x = power_method(G3)
    y = solve_eig(G3)
    
    print(np.round(G3, 2))
    print('Eigenvector', np.round(y, 2))
    print('Eigenvalues', np.round(np.linalg.eigvals(G3), 2))

[[ 0.   0.   0.5  0. ]
 [ 0.   0.   0.5  0. ]
 [ 1.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]]
Eigenvector [ 0.5   0.5   0.71  0.  ]
Eigenvalues [ 0.    0.71 -0.71  0.  ]


## Solucions

Per evitar tenir cicles, graphs separats i dangling nodes, el que es fa és modificar la matriu G amb "soroll", per tal de que tot quedi connectat amb tot. Aquesta tècnica a vegades rep el nom de "Random Surfer".

$$M = (1 - m)G + mS$$

On $S$ és una matriu amb totes les entrades $1/n$ i $m$ un nombre petit, normalment $0.15$.

**Fes una funció que donada la matriu $G$ i $m$ calculi la nova matriu $M$**

In [5]:
Gpro = np.asarray((
        (0,     1/2.0, 1/2.0, 1/3.0), 
        (1/2.0, 0,     0,     1/3.0), 
        (0,     0,     0,     1/3.0), 
        (1/2.0, 1/2.0, 1/2.0, 0)))
print(len(Gpro))



4


In [6]:
def fix_matrix(G, m=0.15):
    S = np.ones([G.shape[0],G.shape[0]])/G.shape[0]
    return ( (G*(1-m)) + (S*m) ) # we apply the Random Surfer technique

In [7]:
if __name__ == '__main__':
    M2 = fix_matrix(G2)
    x = power_method(M2)
    y = solve_eig(G2)
    z = solve_eig(M2)
    
    print(np.round(M2, 2))
    print('Eigenvector', np.round(x, 2))
    print('Eigenvector', np.round(y, 2))
    print('Eigenvector', np.round(z, 2))
    print('Eigenvalues', np.round(np.linalg.eigvals(M2), 2))

[[ 0.03  0.45  0.45  0.03  0.03]
 [ 0.45  0.03  0.45  0.03  0.03]
 [ 0.45  0.45  0.03  0.03  0.03]
 [ 0.03  0.03  0.03  0.03  0.88]
 [ 0.03  0.03  0.03  0.88  0.03]]
Eigenvector [ 0.45  0.45  0.45  0.45  0.45]
Eigenvector [ 0.    0.    0.    0.71  0.71]
Eigenvector [ 0.45  0.45  0.45  0.45  0.45]
Eigenvalues [-0.43  1.    0.85 -0.43 -0.85]


In [8]:
if __name__ == '__main__':
    M3 = fix_matrix(G3)
    x = power_method(M3)
    y = solve_eig(G3)
    z = solve_eig(M3)
    
    print(np.round(M3, 2))
    print('Eigenvector', np.round(x, 2))
    print('Eigenvector', np.round(y, 2))
    print('Eigenvector', np.round(z, 2))
    print('Eigenvalues', np.round(np.linalg.eigvals(M3), 2))

[[ 0.04  0.04  0.46  0.04]
 [ 0.04  0.04  0.46  0.04]
 [ 0.89  0.04  0.04  0.04]
 [ 0.04  0.04  0.04  0.04]]
Eigenvector [ 0.51  0.51  0.69  0.09]
Eigenvector [ 0.5   0.5   0.71  0.  ]
Eigenvector [ 0.51  0.51  0.69  0.09]
Eigenvalues [ 0.72 -0.6   0.03  0.  ]


# Recomanant

El primer que haurem de fer és construir una matriu que ens serveixi, d'alguna forma, com a indicatiu de preferències de cada persona. Per tal efecte, construirem una matriu $m\times n$, de $m$ usuaris per $n$ items, on cada entrada $i,j$ serà el nombre de vegades que la persona $i$ a comprat l'item $j$.

<img src="img/Mat.png">

Per saber de quin usuari és cada `order_id`, haureu de creaur el dataset `order_products` amb el `orders`. Una sola persona/usuari tindrà més d'una ordre, mireu quants cops ha comprat els mateixos productes.

A més, les dades es composen de molts `product_id` diferents, hi ha massa diversitat entre usuaris. Per tant, per poder recomanar el que farem serà agregar les dades, enlloc de treballar per `product_id` ho farem per `aisle_id`, és a dir "la secció" del súper on es troba.

Al llarg de la pràctica es parlarà de producte i/o item, doncs és la terminologia estàndard de recomanadors, però sempre serà en referència a `aisle_id` per aquesta pràctica!

In [9]:
import zipfile
from os.path import join, dirname

def locate(*path):
    base = globals().get('__file__', '.')
    return join(dirname(base), *path)

def unzip(file):
    zip_ref = zipfile.ZipFile(locate(file), 'r')
    zip_ref.extractall(locate('data'))
    zip_ref.close()

unzip('order_products__train.csv.zip')
unzip('orders.csv.zip')
unzip('products.csv.zip')

In [10]:
import pandas as pd

if __name__ == '__main__':
    df_order_prods = pd.read_csv(locate('data', 'order_products__train.csv'))
    df_orders = pd.read_csv(locate('data', 'orders.csv'))[['order_id', 'user_id']]
    df_prods = pd.read_csv(locate('data', 'products.csv'))[['product_id', 'aisle_id']]
    df_order_prods.head()

In [11]:
if __name__ == '__main__':
    # we merge the df_order_prods and df_orders
    df_merged = pd.merge(df_orders, df_order_prods, on = 'order_id')
    
    # we merge the df obtained previously with df_products
    df_merged = pd.merge(df_merged, df_prods, on = 'product_id')
    
    # we just keep the information we want to use
    df_merged = df_merged[['user_id','product_id','aisle_id']]
    
"""The way we are working with data may cause trouble with the test autograder, it would be nice to keep that in mind"""

"Es probable que el test peti, per tant m'agradaria tenir-ho en compte"

Fes la funció que retorna els productes comprats en cada `aisle_id` per cada `user_id`.

In [12]:
def build_counts_table(df):
    """
    Retorna un dataframe on les columnes són els `aisle_id`, les files `user_id` i els valors
    el nombre de vegades que un usuari ha comprat un producte d'un `aisle_id`
    
    :param df: DataFrame original després de creuar-lo
    :return: DataFrame descrit adalt
    """
    # Using size, unstack and fillna we count the number of times a user has bought a product 
    # from each aisle_id, also with fillna we remove all the NaN and set them as 0s
    return df.groupby(['user_id','aisle_id']).size().unstack().fillna(0)

def get_count(df, user_id, aisle_id):
    """
    Retorna el nombre de vegades que un usuari ha comprat en un `aisle_id`
    
    :param df: DataFrame retornat per `build_counts_table`
    :param user_id: ID de l'usuari
    :param aisle_id: ID de la secció
    :return: Enter amb el nombre de vegades que ha comprat
    """
    # using user_id and aisle_id we return the number of times a user has bought a product in that aisle
    return df.at[user_id,aisle_id]

In [14]:
if __name__ == '__main__':
    df_counts = build_counts_table(df_merged)
    count = get_count(df_counts, 1, 77)
    print(count)

2.0


Tenim moltes dades en el nostre dataset, pel que és convenient que les reduïm una mica. Per començar a treballar recomanem que reduiu el tamany a aproximadament 0.001 de l'original (`frac=0.001`). Podeu provar, més endavant, amb 0.01.

A més, necessitem poder provar quan bé funciona el nostre sistema. Pel que dividirem les dades de cada usuari en 2 parts:

1. **Train**: Els items que farem servir per entrenar el nostre recomanador
2. **Test**: Dades "ocultes" que ens serviran per provar quant bé funciona el sistema

**Nota** Pot tardar bastant aquesta cel·la!

def at(row, i):
    if isinstance(row, pd.Series):
        return row.iloc[i]
    
    idxs = np.zeros_like(row)
    idxs[i] = 1
    return idxs * row

def train_test_split(row, test_size, random_state):
    data = row[row > 0]
    nonzero = np.where(row)[0]
    n = len(data)
    t = round(n*test_size)
        
    if n == 0:
        return np.zeros_like(row), np.zeros_like(row)
    elif t == 0:
        return (row > 0).astype(int) * row, np.zeros_like(row)
    
    np.random.seed(random_state)
    
    idxs = range(n)
    idx = np.random.choice(idxs, size=t, 
                           replace=False)
    
    return (
        at(row, nonzero[list(set(idxs) - set(idx))]), 
        at(row, nonzero[idx])
    )
    
    
#from sklearn.model_selection import train_test_split

def iter_counts(df):
    if isinstance(df, pd.DataFrame):
        for uid, row in df.iterrows():
            yield uid, row
    else:
        for i in range(df.shape[0]):
            yield i, df[i]

def split_train_test(df):
    """
    No modifica l'estructura del DataFrame original,
    únicament el divideix en 2 sub-DataFrame's.
    
    Tots dos tenen el mateix nombre d'usuaris, però cada
    un té un conjunt diferent de producte d'aquest
    
    :param df: DataFrame retornat per `build_counts_table`
    :return: Dos DataFrames amb diferents productes
    """
    split = [train_test_split(row, test_size=0.3, random_state=uid) \
                for uid, row in iter_counts(df)]
    
    train, test = [x[0] for x in split], [x[1] for x in split]
    
    if isinstance(df, pd.DataFrame):
        train = pd.DataFrame(train).fillna(0)
        test = pd.DataFrame(test).fillna(0)
        return train, test
        
    return np.array(list(train)), np.array(list(test))



if __name__ == '__main__':    
    df_counts_train, df_counts_test = split_train_test(df_counts.as_matrix())

if __name__ == '__main__':
    FRAC = 0.001
    rows = df_counts_train.shape[0]
    idxs = range(rows)

    np.random.seed(1)
    train_idxs = np.random.choice(idxs, size=int(rows * FRAC), replace=False)
    df_reduced_counts_train = df_counts_train[train_idxs]

    np.random.seed(1)
    test_idxs = np.random.choice(idxs, size=int(rows * FRAC), replace=False)
    df_reduced_counts_test = df_counts_test[test_idxs]
    print(df_reduced_counts_train.shape)
    print(df_reduced_counts_test.shape)

In [15]:
from sklearn.model_selection import train_test_split

def split_train_test(df):
    """
    No modifica l'estructura del DataFrame original,
    únicament el divideix en 2 sub-DataFrame's.
    
    Tots dos tenen el mateix nombre d'usuaris, però cada
    un té un conjunt diferent de producte d'aquest
    
    :param df: DataFrame retornat per `build_counts_table`
    :return: Dos DataFrames amb diferents productes
    """
    split = lambda i: (
        train_test_split(row[row > 0], test_size=0.3, random_state=uid)[i] \
        for uid, row in df.iterrows()
    )
    train = pd.DataFrame(split(0)).fillna(0)
    test = pd.DataFrame(split(1)).fillna(0)
    return train, test

if __name__ == '__main__':    
    df_counts_train, df_counts_test = split_train_test(df_counts)

In [16]:
if __name__ == '__main__':
    FRAC = 0.001
    df_reduced_counts_train = df_counts_train.sample(frac=FRAC, random_state=1)
    df_reduced_counts_test = df_counts_test.sample(frac=FRAC, random_state=1)
    
    print(df_reduced_counts_test.shape)
    print(df_reduced_counts_train.shape)

(131, 134)
(131, 134)


In [17]:
df_reduced_counts_train

aisle_id  1    2    3    4    5    6    7    8    9    10  ...   125  126  \
93427     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
21772     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
8699      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
181653    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
151077    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
142317    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
32177     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
65666     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
200645    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
10212     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
16194     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
76753     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
8696      0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
38447     0.0  0.0  0.0  2.0  0.0  0.0  0.0  0.0  2.0  0.0 ...   0.0  0.0   
55074     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
51386     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
139483    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
107402    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
189443    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  1.0   
45630     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
166147    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
21075     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
165539    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
193544    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
205532    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
15554     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
134866    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
16332     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
102641    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
114339    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ... ...   ...  ...   
205902    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
63175     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
128733    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
67361     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
174510    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
130694    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
121695    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
92338     0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
104023    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
150053    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
992       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
80517     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
58389     0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
181402    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0 ...   0.0  0.0   
9250      1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
112669    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
120579    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
182655    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
136641    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0   
139015    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0

# Graph ampliat

Si ara construíssim un graph com el que fèiem per les webs i generessim el vector principal, obtindríem efectívament un vector amb la importància de cada persona... però, relativa a que?

<img src="img/Matvs.png">

Per tal de solucionar aquest problema, on no sabem que és que del pagerank resultant, el que farem serà ampliar el graph, en certa forma duplicant la informació que tenim. 

<img src="img/Matext.png">

Hauràs de construir una matriu $m+n \times n+m$, on:

* Les $m$ primeres files i les $n$ últimes columnes (indexos $0,m$) sigui la matriu que has construit anteriorment **normalitzada**
* Les últimes $n$ files i les primeres $m$ columnes (indexos $m,0$) sigui la matriu anterior però transposada i **normalitzada**
* La resta d'entrades, 0


**normalitzada**: Aquesta matriu $m\times n$ ha d'estar normalitzada per columnes (les columnes han de sumar 1). Per simplificar les imatges i que siguin més entenedores, es fan servir els valors reals. Però és molt important que normalitzeu en el vostre codi!

In [20]:
def get_extended_graph(df_train):
    """
    Calcula el graf ampliat de prodcutes i usuaris a partir de l'original
    
    :param df: Sub-DataFrame del retornat per `build_counts_table`, per training
    :return: El graf ampliat, tal i com està descrit adalt, tenint en compte
        que la suma de cada columna ha de ser 1 (normalitzar les columnes, és a dir
        dividir cada número de la columna pel total de la suma de la mateixa columna)
    """ 
    am_train = df_train.as_matrix() # we save the dataframe as a matrix
    am_trans = am_train.transpose() # we transpose the matrix
    x = am_train.shape[0] 
    y = am_train.shape[1]
    n = x+y 
    am_ampliat = np.zeros((n,n)) # the expanded array has x+y size
    
    am_ampliat[:x,x:] = am_train # we set the data in the expanded array
    am_ampliat[x:,:x] = am_trans 
    am_ampliat= am_ampliat/am_ampliat.sum(axis=0) # normalizing
    am_ampliat = np.nan_to_num(am_ampliat) # we change the NaN values to 0
    return am_ampliat
    

In [21]:
if __name__ == '__main__':
    G = get_extended_graph(df_reduced_counts_train)
    
    

C:\Users\mat.aules\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: RuntimeWarning: invalid value encountered in true_divide


## Recomanació personalitzada


Seguim tenint un altre problema, i és, estem personalitzant res? La matriu ampliada és exactament la mateixa per cada usuari, independentment del que hagi comprat, i per tant el resultat serà sempre el mateix.

Suposa que volem recomanar a l'usuari 1, el que farem serà crear una altre matriu del mateix tamany que l'anterior, on tots els elements seran 0 excepte aquelles files i columnes (corresponents a la matriu ampliada anterior) dels items que ha comprat l'usuari.

<img src="img/Matper.png">

Finalment, la matriu sobre la qual farem el càlcul de pagerank serà la matriu ampliada perturbada per aquesta nova matriu.

Anomena $G$ a la original i $E$ a aquesta que acabes de fer, i $\bar{E}$ és $E$ normalitzada per columnes, la matriu final $G_m$ serà:

$$G_m = (1-m)G + m\bar{E}$$

Que ja us hauria de sonar! Ho hem fet abans amb pagerank. Fixeu-vos que per cada usuari la matriu $G_m$ serà diferent, doncs tot i que $G$ no canvia, sí que ho fa $E$

In [24]:
def personalize(G, df_train, user, m=0.15):
    """
    Personalitza el graf ampliat per a un usuari donat.
    
    La matriu E, un cop construida i abans de fer-la servir per personalitzar G,
    s'ha de normalitzar per columnes.
    
    :param G: El graf ampliat
    :param df: Sub-DataFrame del retornat per `build_counts_table`, per training
    :param user: ID d'usuari
    :param m: Valor de perturbació, tal i com està descrit adalt
    :return: Matriu ampliada personalitzada
    """
    array_items = df_train.loc[user].tolist() # we get the array of items from the user as list
    x = df_train.shape[0] 
    E = G.copy()
    for i in range(len(array_items)): # we set the E values
        if array_items[i] == 1.0: # if there is a 1 in the user list
            E[:,x+i] = 1 # we set to 1 rows and columns
            E[x+i,:] = 1
    E = E/E.sum(axis=0) # normalizing E
    # applying formula
    E = E*m
    G = G*(1-m)
    return (G+E)
   

In [25]:
if __name__ == '__main__':
    Gm = personalize(G, df_reduced_counts_train, 93427)


In [26]:
Gm

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

Finalment, ara que ja tenim $G_m$, podem executar pagerank i obtenir el vector principal. Com pots observar a la última imatge, aquest vector tindrà $m+n$ elements, els primers $m$ corresponents als usuaris i els següents $n$ als items.

Com que volem similituds entre usuaris, ens quedarem solament amb la primera part, fins a $m$. A més, el propi usuari a qui hem personalitzat la matriu no l'hem de tenir en compte, així que cal posar-l'ho a 0.

In [27]:
def sims_vect(Gm, df_train, user):
    """
    Calcula el vector de similituds per a un usuari donat, és a dir
    executa el metòde de la potència sobre el graf ampliat personalitzat
    de l'usuari, i en retornaels primers M elements del vector resultant.
    
    A més, posa a 0 la posició del vector corresponent a l'usuari al que
    estem recomanant.
    
    :param Gm: Graf ampliat personalitzat
    :param df: Sub-DataFrame del retornat per `build_counts_table`, per training
    :param user: ID de l'usuari
    :return: Vector de similituds en una array de numpy
    """
    vect = power_method(Gm) # we use the power method on the graph
    i_user = df_train.index.tolist().index(user) # we get the user index
    vect = vect[:df_train.shape[0]] # we get the vector of sims
    vect[i_user] = 0 # set the user value to 0
    return vect # return the sims vector

In [28]:
if __name__ == '__main__':
    sims = sims_vect(Gm, df_reduced_counts_train, 93427)

In [156]:
sum(sims)

3.5519097242501556

Ara aplica la formula per recomanacions colaboratives donat un usuari $u$ i item $i$

$$\hat{r}_{u,i} = \frac{\sum_{p,p\neq u} sim(u,p) \cdot r_{p,i}}{\sum_p sim(u,p)}$$

Tingues en compte que aquesta fòrmula solament té en compte aquells usuaris que també han comprat el mateix! Si no han comprat, no s'ha de comptar en el sumatori!

In [94]:
def score(df_train, user, item, sims):
    """
    Fent servir la fòrmula del filtratge colaboratiu, retorna un valor
    per a un usuari i producte
    
    :param df: Sub-DataFrame del retornat per `build_counts_table`, per training
    :parma user: ID de l'usuari
    :param item: ID de l'item
    :param sims: Vector de similituds per a l'usuari
    :return: Un flotant indicant el valor computat segons la fòrmula d'adalt
    """
    users_total = 0 
    users_parcial = 0
    valor=df_train.loc[:,item].tolist()
    # we apply the formula
    for i in range(len(sims)):
        users_parcial += sims[i]*valor[i]
        if valor[i] != 0:
            users_total += sims[i]
    return float(users_parcial/users_total)

In [95]:
if __name__ == '__main__':
    print(score(df_reduced_counts_train, 93427, 98, sims))
    print(df_reduced_counts_test.loc[93427, 98])
    print(df_reduced_counts_train.loc[93427, 98])

1.3164415303119963
1.0
0.0


Ara, donat un usuari, recomana-li els $k$ millors productes que podria comprar. Per fer-ho, computa l'`score` per a cada possible item que encara no hagi comprat, ordena i retorna els $k$ millors.

Si $k=0$, significa retornar tots els possibles.

In [160]:
def recommend(df_train, sims, user, k, score=score):
    """
    Calcula l'`score` de tots els items d'un usuari, que no hagin estat ja comprats,
    i retorna els $k$ amb valor més alt. Si $k=0$, els retorna tots ordenats de major a menor.
    
    :param df: Sub-DataFrame del retornat per `build_counts_table`, per training
    :param sims: Vector de similituds
    :param user: ID de l'usuari
    :param k: Número de valors a retornar, o 0 per tots
    :param score: Funció a fer servir per calcular l'score
    :return: Llista amb els $k$ (o tots si $k=0$) items més alts. Cada element d'aquest
        vector serà una tupla (valor, aisle_id)
    """
    items_list = list(df_reduced_counts_train.keys())
    score_list = []
    for i in items_list: # for each item from a user
        if df_train.at[user,i] != 1: # if its not already bought
            # we calculate the score
            s =score(df_train, user, i, sims)
            # if the number is different than itself, it means that the value isnt a Real number, its a Nan
            if s != s:
                s = 0
            # and append the value to the list
            score_list.append((s,i))
    
    if k == 0:
        return sorted(score_list,reverse=True)
    return sorted(score_list,reverse=True)[:k]    

In [161]:
if __name__ == '__main__':
    print(recommend(df_reduced_counts_train, sims, 93427, 5))

[(2.4411622570751152, 38), (2.4000425238428957, 24), (2.290482890097705, 123), (2.0, 46), (2.0, 22)]


C:\Users\mat.aules\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: RuntimeWarning: invalid value encountered in double_scalars


## Evaluant

Per saber si em fet un bon recomanador, hem d'avaluar si està funcionant correctament. Ho farem predint la puntuació de tots els items de test per un usuari, i comparant amb els valors reals.

Les funcions ja estan fetes, simplement podeu executar per veure que us surt un nombre raonable.

In [121]:
def evaluate(df_train, df_test, sims, user, score=score):
    real = df_test.loc[user]
    pred_list = recommend(df_train, sims, user, 0, score=score)
    pred = pd.Series({y: x for x, y in pred_list})
    
    real = real[real > 0]
    pred = pred.loc[real.index]
    
    return np.sum(np.power(real - pred, 2))
        

def mean_eval(df_train, df_test, users, score=score):
    G = get_extended_graph(df_train)
    return np.mean([
        evaluate(
            df_train, 
            df_test, 
            sims_vect(personalize(G, df_train, uid), df_train, uid), 
            uid,
            score=score
        ) \
        for uid in users if df_train.loc[uid].sum() > 0
    ])

In [122]:
if __name__ == '__main__':
    print(evaluate(df_reduced_counts_train, df_reduced_counts_test, sims, 93427))

0.4124348650235776


C:\Users\mat.aules\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: RuntimeWarning: invalid value encountered in double_scalars


In [123]:
if __name__ == '__main__':
    users = df_reduced_counts_test.sample(n=10).index
    print(mean_eval(df_reduced_counts_train, df_reduced_counts_test, users))

C:\Users\mat.aules\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: RuntimeWarning: invalid value encountered in true_divide


1.17919602508


C:\Users\mat.aules\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: RuntimeWarning: invalid value encountered in double_scalars


In [60]:
print(users)

Int64Index([104813, 55709, 20040, 10212, 15554, 45226, 200645, 116688, 10420,
            107813],
           dtype='int64')


# Propostes de millora

## 1. Millorar la recomanació colaborativa

La fòrmula que fem servir per calcular l'`score`, basada en la recomanació colaborativa, és força inexacta, doncs no té en compte el *bias* introduit per la mitja del comprador.

Per exemple, jo potser tinc família numerosa i compro sempre 5 del mateix producte com a mínim, mentre que algú que visqui sol únicament en compraria 1 unitat.

Podem eliminar aquest bias fent:

$$\hat{r}_{u,i} = \frac{\sum_{v,v\neq u} sim(u,v) \cdot (r_{v,i} - \mu_v)}{\sum_{v,v\neq u} sim(u,v)} + \mu_u$$

És a dir, a cada producte d'altres persones li restem la mitja d'aquella persona ($\mu_v$) i al final reintroduïm la mitja de l'usuari a qui estem recomanant ($\mu_u$)

In [162]:
def score_mean(df_train, user, item, sims):    
    users_total = 0
    users_parcial = 0
    valor=df_train.loc[:,item].tolist()
    uList = np.nan_to_num(list(df_train.sum(axis=1)/(df_reduced_counts_train.loc[:]>0).sum(axis=1))) # we calculate every U value
    for i in range(len(sims)): # for each item
        if valor[i] != 0: # if the value is different than 0
            users_parcial += sims[i]*(valor[i]-uList[i])# we apply the formula
            users_total += sims[i]
    i_user = df_train.index.tolist().index(user) # we get the user index
    if users_total == 0: return 0 #if this value is 0 we return 0 as we cant divide by 0
    return float(users_parcial/users_total)+uList[i_user] # we return the calculated score

In [163]:
if __name__ == '__main__':
    print(score_mean(df_reduced_counts_train, 93427, 98, sims))

0.89963758286


In [165]:
if __name__ == '__main__':
    print(mean_eval(df_reduced_counts_train, df_reduced_counts_test, users, score=score_mean))

C:\Users\mat.aules\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: RuntimeWarning: invalid value encountered in true_divide


1.56211482672


**Nota**: Recalcular les mitges cada cop és molt lent, probablement voldràs tenir-les precalculades (amb una variable global o semblant)

## 2. Utilitzar més dades

Una simple inspecció de la taula de comptes, ens mostrarà que un gran percentatge està buida:

In [ ]:
if __name__ == '__main__':
    total = np.prod(df_counts.shape)
    zero = (df_counts == 0).sum().sum()
    nonzero = total - zero

    print('Are 0: {:2.3g}%'.format(zero / total * 100))

Per tant, podríem pensar que enlloc de guardar absolutament tot, solament necessitem saber les posicions on no hi ha 0's i el seu valor. Això és precisament el que fan les estructures de la llibreria

```python
import scipy.sparse as sparse
```

Tot el contingut de la llibreria `sparse` són presentacions no denses de matrius, únicament guarden els elements que són diferents de 0.

Es proposa que canvieu les funcions `get_extended_matrix` i `personalize` per tal de que facin servir `sparse.lil_matrix` enlloc de `np.array`, i que augmenteu `FRAC` a `1.0` (totes les dades).

**Nota**: No es tracta d'un procés trivial, treballar amb matrius sparse té cert misteri. 

**1.** No feu servir mai funcions de numpy sobre una matriu sparse, per exemple, supossa que `mat` és una `sparse.lil_matrix` i `dia` una matriu diagonal també `sparse.lil_matrix`:

```python
res = np.dot(mat, dia)
```

Farà el producte matricial, però la matriu resultant `res` no serà sparse sinó densa. Feu servir sempre la versió "metòdica" de les funcions:

```python
res = mat.dot(dia)
```

I ara, `res` és sparse, tal i com s'espera.

------------------

**2.** Si vols agafar una columna sencera i convertir-la a un vector dens, tal i com faria numpy, no és suficient fent:

```python
col = mat[:,0]
```

Doncs el resultat, no és un vector de $n$ elements, sinó una matriu $n,1$. Podríem pensar que aplanar el vector resultaria:

```python
col = mat[:,0].flatten() # O, equivalentment, mat[:,0].ravel()
``` 

Però tampoc funcionarà. Cal convertir explícitament a array de numpy abans:

```python
col = np.array(mat[:,0]).ravel() # o flatten()
```

I, ara sí, tenim un vector de $n$ elements.